#!/usr/bin/env bun
/**
 * Extracts ABIs from contracts/out/ and writes typed TS files
 * into packages/contracts-abi/src/generated/
 *
 * Usage: bun tooling/scripts/extract-abis.ts
 * Or via: pnpm contracts:abi
 */
// import { readFileSync, writeFileSync, mkdirSync } from "fs";
// import { resolve, dirname } from "path";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const CONTRACTS_OUT = resolve("contracts/out");
const ABI_OUT = resolve("packages/contracts-abi/src/generated");

const CONTRACTS = [
  "LogersAccount",
  "LogersAccountFactory",
  "LogersPaymaster",
  "LogersPriceOracle",
] as const;

mkdirSync(ABI_OUT, { recursive: true });

for (const name of CONTRACTS) {
  const artifactPath = resolve(CONTRACTS_OUT, `${name}.sol`, `${name}.json`);

  let artifact: { abi: unknown[] };
  try {
    artifact = JSON.parse(readFileSync(artifactPath, "utf-8")) as { abi: unknown[] };
  } catch {
    console.warn(`⚠️  ${name}: artifact not found at ${artifactPath}, skipping`);
    continue;
  }

  const varName = `${name.charAt(0).toLowerCase()}${name.slice(1)}Abi`;
  const content = `// Auto-generated by tooling/scripts/extract-abis.ts
// Do not edit manually — run: pnpm contracts:abi
// Source: contracts/out/${name}.sol/${name}.json

export const ${varName} = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

  const outPath = resolve(ABI_OUT, `${name}.abi.ts`);
  writeFileSync(outPath, content, "utf-8");
  // biome-ignore lint/suspicious/noConsoleLog: CLI script output
  console.log(`✅ ${name} → ${outPath}`);
}

// biome-ignore lint/suspicious/noConsoleLog: CLI script output
console.log("\n✅ ABI extraction complete");
